// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function valueFromEvent(evt) {
  return evt.target.value;
}

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("TodoItem");

function make(item, onToggle, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var checked = Js_boolean.to_js_boolean(item[/* completed */2]);
      return React.createElement("div", {
                  className: "item",
                  onClick: (function () {
                      return Curry._1(onToggle, /* () */0);
                    })
                }, React.createElement("input", {
                      checked: checked,
                      type: "checkbox"
                    }), item[/* title */1]);
    });
  return newrecord;
}

var TodoItem = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.reducerComponent("Input");

function make$1(onSubmit, _) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function (param) {
      var text = param[/* state */2];
      var reduce = param[/* reduce */1];
      return React.createElement("input", {
                  placeholder: "Write something to do",
                  type: "text",
                  value: text,
                  onKeyDown: (function (evt) {
                      if (evt.key === "Enter") {
                        Curry._1(onSubmit, text);
                        return Curry._2(reduce, (function () {
                                      return "";
                                    }), /* () */0);
                      } else {
                        return 0;
                      }
                    }),
                  onChange: Curry._1(reduce, (function (evt) {
                          return evt.target.value;
                        }))
                });
    });
  newrecord[/* initialState */10] = (function () {
      return "";
    });
  newrecord[/* reducer */12] = (function (newText, _) {
      return /* Update */Block.__(0, [newText]);
    });
  return newrecord;
}

var Input = /* module */[
  /* component */component$1,
  /* make */make$1
];

var component$2 = ReasonReact.reducerComponent("TodoApp");

var lastId = [0];

function newItem(text) {
  lastId[0] = lastId[0] + 1 | 0;
  return /* record */[
          /* id */lastId[0],
          /* title */text,
          /* completed : true */1
        ];
}

function pluralize(l, name) {
  if (l) {
    if (l[1]) {
      return name + "s";
    } else {
      return name;
    }
  } else {
    return name + "s";
  }
}

function make$2() {
  var newrecord = component$2.slice();
  newrecord[/* didMount */4] = (function (param) {
      setInterval(Curry._1(param[/* reduce */1], (function () {
                  return /* Tick */0;
                })), 1000);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var match = param[/* state */2];
      var items = match[/* items */1];
      var reduce = param[/* reduce */1];
      var numItems = List.length(items);
      return React.createElement("div", {
                  className: "app"
                }, React.createElement("div", {
                      className: "title"
                    }, "What to do", ReasonReact.element(/* None */0, /* None */0, make$1(Curry._1(reduce, (function (text) {
                                    return /* AddItem */Block.__(0, [text]);
                                  })), /* array */[]))), React.createElement("div", {
                      className: "items"
                    }, $$Array.of_list(List.map((function (item) {
                                var key = Pervasives.string_of_int(item[/* id */0]);
                                return ReasonReact.element(/* Some */[key], /* None */0, make(item, Curry._1(reduce, (function () {
                                                      return /* ToggleItem */Block.__(1, [item[/* id */0]]);
                                                    })), /* array */[]));
                              }), items))), React.createElement("div", {
                      className: "footer"
                    }, Pervasives.string_of_int(numItems) + (" " + pluralize(items, "item"))), React.createElement("div", {
                      className: "footer"
                    }, Pervasives.string_of_int(match[/* count */0])));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* count */0,
              /* items : :: */[
                /* record */[
                  /* id */0,
                  /* title */"Write some things to do",
                  /* completed : false */0
                ],
                /* [] */0
              ]
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (typeof action === "number") {
        return /* Update */Block.__(0, [/* record */[
                    /* count */state[/* count */0] + 1 | 0,
                    /* items */state[/* items */1]
                  ]]);
      } else if (action.tag) {
        var id = action[0];
        var items = List.map((function (item) {
                var match = +(item[/* id */0] === id);
                if (match !== 0) {
                  return /* record */[
                          /* id */item[/* id */0],
                          /* title */item[/* title */1],
                          /* completed */1 - item[/* completed */2]
                        ];
                } else {
                  return item;
                }
              }), state[/* items */1]);
        return /* Update */Block.__(0, [/* record */[
                    /* count */state[/* count */0],
                    /* items */items
                  ]]);
      } else {
        return /* Update */Block.__(0, [/* record */[
                    /* count */state[/* count */0],
                    /* items : :: */[
                      newItem(action[0]),
                      state[/* items */1]
                    ]
                  ]]);
      }
    });
  return newrecord;
}

exports.valueFromEvent = valueFromEvent;
exports.str            = str;
exports.TodoItem       = TodoItem;
exports.Input          = Input;
exports.component      = component$2;
exports.lastId         = lastId;
exports.newItem        = newItem;
exports.pluralize      = pluralize;
exports.make           = make$2;
/* component Not a pure module */
